<a href="https://colab.research.google.com/github/Archanapy76/breast-cancer-classification/blob/main/Assignment7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

ModuleNotFoundError: No module named 'skleran'

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [10]:
data = load_breast_cancer()
X = pd.DataFrame(data.data, columns=data.feature_names)
y= pd.Series(data.target, name='target')
X.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [12]:
X.isnull().sum().sum()

np.int64(0)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [28]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [33]:
logisticmodel = LogisticRegression(max_iter=10000, random_state=42)
logisticmodel.fit(X_train_scaled, y_train)
y_pred_logistic = logisticmodel.predict(X_test_scaled)
print(classification_report(y_test, y_pred_logistic))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        42
           1       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

In [37]:
decison_tree = DecisionTreeClassifier(random_state=42)
decison_tree.fit(X_train, y_train)
Y_pred_tree = decison_tree.predict(X_test)
print(classification_report(y_test, Y_pred_tree))

              precision    recall  f1-score   support

           0       0.85      0.93      0.89        42
           1       0.96      0.90      0.93        72

    accuracy                           0.91       114
   macro avg       0.90      0.92      0.91       114
weighted avg       0.92      0.91      0.91       114

In [38]:
random_forest = RandomForestClassifier(n_estimators=100, random_state=42)
random_forest.fit(X_train, y_train)
Y_pred_rf = random_forest.predict(X_test)
print(classification_report(y_test, Y_pred_rf))

              precision    recall  f1-score   support

           0       0.95      0.93      0.94        42
           1       0.96      0.97      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

In [43]:
svm_model =SVC(kernel ="rbf",random_state=42)
svm_model.fit(X_train_scaled,y_train)
y_pred_svm = svm_model.predict(X_test_scaled)
print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        42
           1       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

In [39]:
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled,y_train)
knn_model.fit(X_train_scaled,y_train)
y_pred_knn = knn_model.predict(X_test_scaled)
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.95      0.93      0.94        42
           1       0.96      0.97      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

In [47]:
models = {
    "log_reg":y_pred_logistic,
    "dec_tree":Y_pred_tree,
    "r_forest":Y_pred_rf,
    "svm":y_pred_svm,
    "knn":y_pred_knn
}
results =[]
for model_name, predictions in models.items():
      results.append({
    "Model": model_name,
    "Accuracy":accuracy_score(y_test,predictions),
    "Confusion Matrix": confusion_matrix(y_test,predictions),
    "Classification Report": classification_report(y_test,predictions)})
result_df = pd.DataFrame(results)
result_df.sort_values(by="Accuracy",ascending=False)

,Model,Accuracy,Confusion Matrix,Classification Report
0,log_reg,0.982456,"[[41, 1], [1, 71]]",precision recall f1-score ...
3,svm,0.982456,"[[41, 1], [1, 71]]",precision recall f1-score ...
2,r_forest,0.956140,"[[39, 3], [2, 70]]",precision recall f1-score ...
4,knn,0.956140,"[[39, 3], [2, 70]]",precision recall f1-score ...
1,dec_tree,0.912281,"[[39, 3], [7, 65]]",precision recall f1-score ...

In [51]:
 best_model = result_df.loc[result_df["Accuracy"].idxmax()]
 print(best_model)

Model                                                              log_reg
Accuracy                                                          0.982456
Confusion Matrix                                        [[41, 1], [1, 71]]
Classification Report                  precision    recall  f1-score   ...
Name: 0, dtype: object

In [52]:
worst_model = result_df.loc[result_df["Accuracy"].idxmin()]
print(worst_model)

Model                                                             dec_tree
Accuracy                                                          0.912281
Confusion Matrix                                        [[39, 3], [7, 65]]
Classification Report                  precision    recall  f1-score   ...
Name: 1, dtype: object